const palette = {
  "bg-canvas": "#090d14",
  "bg-shell": "#111724",
  "bg-rail": "#1b2232",
  "bg-surface": "#20283a",
  "bg-panel": "#262f43",
  "bg-elevated": "#2d3650",
  "msg-primary": "#5c7cff",
  "msg-danger": "#ff3b3b",
  "msg-warning": "#ffb800",
  "msg-accent": "#8a2be2",
  "text-primary": "#edf2ff",
  "text-secondary": "#b5bed2",
  "text-muted": "#7e8698",
  "text-quiet": "#5e6678",
  "border-subtle": "#3b4357",
  "border-strong": "#55607a",
  "border-accent": "#6d7de4",
  success: "#22c55e",

  // Transitional aliases for existing class usage.
  background: "#090d14",
  foreground: "#edf2ff",
  surface: "#20283a",
  primary: "#5c7cff",
  accent: "#8a2be2",
  muted: "#5e6678",
  border: "#3b4357",
  danger: "#ff3b3b",
  warning: "#ffb800",
}

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "bg-canvas": palette["bg-canvas"],
        "bg-shell": palette["bg-shell"],
        "bg-rail": palette["bg-rail"],
        "bg-surface": palette["bg-surface"],
        "bg-panel": palette["bg-panel"],
        "bg-elevated": palette["bg-elevated"],
        "msg-primary": palette["msg-primary"],
        "msg-danger": palette["msg-danger"],
        "msg-warning": palette["msg-warning"],
        "msg-accent": palette["msg-accent"],
        "text-primary": palette["text-primary"],
        "text-secondary": palette["text-secondary"],
        "text-muted": palette["text-muted"],
        "text-quiet": palette["text-quiet"],
        "border-subtle": palette["border-subtle"],
        "border-strong": palette["border-strong"],
        "border-accent": palette["border-accent"],
        background: palette.background,
        foreground: palette.foreground,
        surface: palette.surface,
        primary: palette.primary,
        accent: palette.accent,
        muted: palette.muted,
        border: palette.border,
        success: palette.success,
        danger: palette.danger,
        warning: palette.warning,
      },
      borderRadius: {
        panel: "1.75rem",
        shell: "2rem",
      },
      boxShadow: {
        rail: "0 24px 60px -40px rgba(3, 8, 18, 0.95)",
        panel: "0 24px 64px -42px rgba(3, 8, 18, 0.9)",
        active: "0 14px 32px -24px rgba(92, 124, 255, 0.7)",
      },
      fontFamily: {
        display: [
          '"Aptos Display"',
          '"Segoe UI Variable Display"',
          '"Noto Sans TC"',
          '"Microsoft JhengHei"',
          "sans-serif",
        ],
        body: [
          '"Aptos"',
          '"Segoe UI Variable Text"',
          '"Noto Sans TC"',
          '"Microsoft JhengHei"',
          "sans-serif",
        ],
        mono: ['"JetBrains Mono"', '"Cascadia Code"', "monospace"],
      },
    },
  },
  plugins: [],
}
