export const SERVER = "http://localhost:8080"

// Safe fallback values (last resort only). Source: previously hard-coded defaults in UI.
export const DEFAULT_POLL_INTERVAL_SECONDS = 5
export const DEFAULT_MONITORING_STATUS_POLL_INTERVAL_SECONDS = 5
export const DEFAULT_BATCH_SIZE = 8
export const DEFAULT_MAX_CONCURRENCY = 1
export const LIVE_VIEW_MAX_STREAMS = 4
export const LIVE_VIEW_FLOATING_BREAKPOINT = 1024
export const LIVE_VIEW_WINDOW_DEFAULT_WIDTH = 440
export const LIVE_VIEW_WINDOW_DEFAULT_HEIGHT = 344
export const LIVE_VIEW_WINDOW_OFFSET = 28
export const LIVE_VIEW_WINDOW_STAGE_PADDING = 16
export const LIVE_VIEW_WINDOW_MIN_WIDTH = 320
export const LIVE_VIEW_WINDOW_MIN_HEIGHT = 220
export const LIVE_VIEW_WINDOW_HEADER_HEIGHT = 54
export const LIVE_STREAM_POPUP_DEFAULT_WIDTH = 1440
export const LIVE_STREAM_POPUP_DEFAULT_HEIGHT = 960
export const LIVE_STREAM_POPUP_DEFAULT_LEFT = 96
export const LIVE_STREAM_POPUP_DEFAULT_TOP = 72
